version: '2'
services:
  rabbit:
    image: rabbitmq:3.6-management
    ports:
      - 5672:5672
      - 15672:15672
  postgres:
    image: postgres:9.5.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: article
      POSTGRES_USER: article
      POSTGRES_PASSWORD: article
  influxdb:
    image: influxdb:latest
    ports:
      - 8086:8086
      - 8083:8083
      - 2003:2003
    environment:
      INFLUXDB_GRAPHITE_ENABLED: "true"
      INFLUXDB_ADMIN_ENABLED: "true"
      INFLUXDB_DB: "article"
      INFLUXDB_ADMIN_USER: "admin"
      INFLUXDB_ADMIN_PASSWORD: "admin"
      INFLUXDB_USER: "user"
      INFLUXDB_USER_PASSWORD: "password"
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"