version: '2'
services:
  rabbit:
    image: rabbitmq:3.6-management
    ports:
      - 5672:5672
      - 15672:15672
  postgres:
    image: postgres:9.5.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: article
      POSTGRES_USER: article
      POSTGRES_PASSWORD: article
  influxdb:
    image: influxdb:latest
    ports:
      - 8086:8086
      - 8083:8083
      - 2003:2003
    environment:
      INFLUXDB_GRAPHITE_ENABLED: "true"
      INFLUXDB_ADMIN_ENABLED: "true"
      INFLUXDB_DB: "article"
      INFLUXDB_ADMIN_USER: "admin"
      INFLUXDB_ADMIN_PASSWORD: "admin"
      INFLUXDB_USER: "user"
      INFLUXDB_USER_PASSWORD: "password"
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
  article:
    build:
      context: .
      args:
        PROJECT: "service"
        PROJECT_DIR: "service"
        BIN_FILE_NAME: "service"
    environment:
      AMQP_HOST: "rabbit"
      DB_LINK: "jdbc:postgresql://postgres:5432/article"
      ELEVIO_TOKEN: "???"
      ELEVIO_API_KEY: "???"
      INFLUX_HOST: "influxdb"
      ZIPKIN_HOST: "zipkin"
    ports:
      - 9000:9000
  updater:
    build:
      context: .
      args:
        PROJECT: "updater"
        PROJECT_DIR: "updater"
        BIN_FILE_NAME: "updater"
    environment:
      AMQP_HOST: "rabbit"
      DB_LINK: "jdbc:postgresql://127.0.0.1:5432/article"
      ELEVIO_TOKEN: "???"
      ELEVIO_API_KEY: "???"
      INFLUX_HOST: "influxdb"
      ZIPKIN_HOST: "zipkin"
      ARTICLE_S_URI: "http://article:9000"
    ports:
      - 9001:9001